# Generated by Django 5.0.7 on 2024-08-12 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0045_usersettings_disabled_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_holder_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=16)),
                ("sort_code", models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name="teammemberpermission",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="team_permissions", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="defaultvalues",
            name="bank_details",
            field=models.ManyToManyField(blank=True, related_name="default_values", to="backend.bankdetail"),
        ),
    ]
